# Generated by Django 2.2.4 on 2020-03-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
