# Generated by Django 2.2.4 on 2020-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200311_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
